import type { Shalgemon } from "./types";

export const SHALGEMON_CATALOG: Shalgemon[] = [
  {
    id: "shlg-001",
    name: "Fulgura",
    element: "Foudre",
    chromaticAffinity: ["Orchidée", "Violet froid"],
    odorNotes: ["ozone", "lavande"],
    signatureSkill: "Arc prismatique",
    temperament: "Vigilante",
    rarity: "Rare",
    stabilityIndex: 78,
  },
  {
    id: "shlg-002",
    name: "Braisiard",
    element: "Braise",
    chromaticAffinity: ["Magenta", "Ambre intense"],
    odorNotes: ["châtaigne grillée", "safran"],
    signatureSkill: "Brasier spectral",
    temperament: "Impulsif",
    rarity: "Épique",
    stabilityIndex: 64,
  },
  {
    id: "shlg-003",
    name: "Nébulea",
    element: "Brume",
    chromaticAffinity: ["Bleu nuit", "Argenté"],
    odorNotes: ["iris", "pluie d’été"],
    signatureSkill: "Voile astral",
    temperament: "Contemplative",
    rarity: "Rare",
    stabilityIndex: 91,
  },
  {
    id: "shlg-004",
    name: "Sylvant",
    element: "Verdure",
    chromaticAffinity: ["Vert mousse", "Citron givré"],
    odorNotes: ["sève", "menthe blanche"],
    signatureSkill: "Canopée chromée",
    temperament: "Posé",
    rarity: "Commun",
    stabilityIndex: 85,
  },
  {
    id: "shlg-005",
    name: "Marélithe",
    element: "Flux",
    chromaticAffinity: ["Turquoise", "Bleu glacier"],
    odorNotes: ["sel de mer", "algue douce"],
    signatureSkill: "Sillage irisé",
    temperament: "Adaptable",
    rarity: "Commun",
    stabilityIndex: 72,
  },
  {
    id: "shlg-006",
    name: "Sépialune",
    element: "Ombre",
    chromaticAffinity: ["Prune sombre", "Argent lunaire"],
    odorNotes: ["musc léger", "fleur de nuit"],
    signatureSkill: "Filtre ténébrolight",
    temperament: "Discrète",
    rarity: "Rare",
    stabilityIndex: 88,
  },
  {
    id: "shlg-007",
    name: "Lithéon",
    element: "Minéral",
    chromaticAffinity: ["Graphite", "Cuivre poli"],
    odorNotes: ["pierre chaude", "cèdre"],
    signatureSkill: "Cohorte spectrale",
    temperament: "Stoïque",
    rarity: "Commun",
    stabilityIndex: 95,
  },
  {
    id: "shlg-008",
    name: "Aérielle",
    element: "Aérien",
    chromaticAffinity: ["Pervenche", "Nacre"],
    odorNotes: ["glycine", "air pur"],
    signatureSkill: "Danse éthérée",
    temperament: "Enjouée",
    rarity: "Rare",
    stabilityIndex: 69,
  },
  {
    id: "shlg-009",
    name: "Quasaros",
    element: "Plasma",
    chromaticAffinity: ["Indigo profond", "Or stellaire"],
    odorNotes: ["ambre bleu", "encens léger"],
    signatureSkill: "Nuée fractale",
    temperament: "Imprévisible",
    rarity: "Mythique",
    stabilityIndex: 58,
  },
  {
    id: "shlg-010",
    name: "Floréon",
    element: "Floraison",
    chromaticAffinity: ["Corail", "Vert tendre"],
    odorNotes: ["pivoine", "herbe fraîche"],
    signatureSkill: "Rayon chlorochrome",
    temperament: "Altruiste",
    rarity: "Commun",
    stabilityIndex: 82,
  },
  {
    id: "shlg-011",
    name: "Cryostel",
    element: "Givre",
    chromaticAffinity: ["Bleu polaire", "Blanc pur"],
    odorNotes: ["menthol", "neige"],
    signatureSkill: "Aiguille spectrale",
    temperament: "Rigoureux",
    rarity: "Épique",
    stabilityIndex: 76,
  },
  {
    id: "shlg-012",
    name: "Solarys",
    element: "Rayon",
    chromaticAffinity: ["Jaune solaire", "Cuivre léger"],
    odorNotes: ["tilleul", "verveine"],
    signatureSkill: "Halo modulant",
    temperament: "Charismatique",
    rarity: "Rare",
    stabilityIndex: 89,
  },
];
